name: build  and deploy unity3d project

on:
  push:
    branches:
      - master

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.3.0f1
        targetPlatform:
          - StandaloneWindows64
          - StandaloneLinux64
          - WebGL
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}

      - uses: webbertakken/unity-builder@v0.9
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: attach build hash to webgl artifact
        run: |
          if [ ! -d "build/WebGL" ]; then exit 0; fi
          ls -al build/WebGL/
          commithash=$(git rev-parse --short ${GITHUB_SHA})
          sed -i -e "s/re_pair/re_pair-$commithash/g" build/WebGL/index.html

      - uses: actions/upload-artifact@v1
        with:
          name: rePAIR-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  deployWebGLBuild:
    needs: buildForSomePlatforms
    name: deploy WebGL build to ggj20.games.roboto.gg
    runs-on: ubuntu-latest
    steps:
      - name: download latest webgl build
        uses: actions/download-artifact@v1
        with:
          name: rePAIR-WebGL
          path: artifact

      - name: deploy artifacts to pages repo
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          repo: robot-o/playrepair
          target_branch: master
          build_dir: artifact/WebGL
          keep_history: true
          commit_message: deployed ${GITHUB_SHA} on gh-pages
        env:
          GITHUB_PAT: ${{ secrets.GH_DEPLOY_LIVE_TOKEN }}
